'use client';
import {useState} from 'react';
import {Sparkles} from 'lucide-react';
import {items,rate,rounds,Student} from './model';
import {expected,needsReview,estimate,probability} from './irt-feedback';
export default function ClassFeedback({students:ss,school,cls,round,onArea,onItem,onStudent,onConsult}:{students:Student[];school:string;cls:string;round:number;onArea:(area:string)=>void;onItem:(j:number,studentId:string)=>void;onStudent:(id:string)=>void;onConsult:()=>void}){
const [showAll,setShowAll]=useState(false);
const areas=[...new Set(items.map(i=>i.area))].map(area=>{const ii=items.filter(i=>i.area===area);const actual=ii.reduce((n,i)=>n+rate(ss,i.id),0)/ii.length;const prediction=ii.reduce((n,i)=>n+(expected(ss,i.id)??0),0)/ii.length;const overall=ii.reduce((n,i)=>n+i.overall,0)/ii.length;return {area,ii,actual,prediction,overall,gap:actual-prediction}});const best=[...areas].sort((a,b)=>b.actual-a.actual)[0];const focus=[...areas].sort((a,b)=>a.gap-b.gap)[0];const flagged=ss.filter(s=>items.some(i=>needsReview(s,i.id)));const evidence=items.filter(i=>ss.some(s=>needsReview(s,i.id)));const diff=(v:number)=>(v>0?'+':'')+v.toFixed(1)+'ポイント';
return <section className="insight class-feedback"><div className="between"><h2>{school!=='all'&&cls!=='all'?'クラス全体への指導提案':'受け持ちの生徒全体への指導提案'}</h2><span className="badge">{school==='all'?'全校':school} / {cls==='all'?'全クラス':cls+'組'} · {ss.length}人 · 数学 · {rounds[round].name}</span></div><p className="muted">指導方針をご検討いただくために、今回の結果から注目点を整理しています。</p>{!ss.length?<p>この条件では分析対象の結果がありません。</p>:<><div className="class-focus"><h3>今回、注意したいポイント</h3><p>{focus.gap<0?`「${focus.area}」は、学力から予測した正答率より実際の正答率が${Math.abs(focus.gap).toFixed(1)}ポイント低い結果です。この領域のどの問題に差が集中しているかが、注目点になります。`:'領域別の正答率に、予測を下回る傾向は見られません。集計だけでは見えない個別の不正解にも留意が必要です。'}</p></div><div className="grid2"><article className="class-observation"><h3>比較的正答できている内容</h3><p>「{best.area}」の正答率は<b>{best.actual.toFixed(1)}%</b>で、今回の領域の中で最も高い結果です。全受験者との差は{diff(best.actual-best.overall)}です。</p><p className="muted">今回出題された{best.ii.length}問の結果です。領域全体の習得を判定するものではありません。</p><button className="textlink" onClick={()=>onArea(best.area)}>根拠の問題を見る →</button></article><article className="class-observation"><h3>全体との比較で気になる内容</h3><p>「{focus.area}」は全受験者の正答率が{focus.overall.toFixed(1)}%、受け持ちの生徒は{focus.actual.toFixed(1)}%です。差は<b>{diff(focus.actual-focus.overall)}</b>です。</p><p className="muted">学力からの予測正答率は{focus.prediction.toFixed(1)}%。平均との差と予測との差を分けて捉える必要があります。原因は正誤だけでは特定できません。</p><button className="textlink" onClick={()=>onArea(focus.area)}>関連する問題を見る →</button></article></div><div className="class-focus"><h3>解答を確認したい生徒</h3><p>解ける可能性が高いと推定された問題で、不正解が見られた生徒です。答案から、理解の抜けや読み違いなどを確認する手掛かりになります。</p><p><b>該当する生徒：{flagged.length}人／対象{ss.length}人</b></p>{flagged.length?<><div className="trend-scroll"><table><thead><tr><th>生徒ID</th><th>確認したい問題数</th><th>問題・学習内容</th></tr></thead><tbody>{(showAll?flagged:flagged.slice(0,5)).map(s=>{const questions=items.filter(i=>needsReview(s,i.id)).sort((a,b)=>probability(estimate(s).theta,b.id)-probability(estimate(s).theta,a.id));const link=(i:typeof items[number])=><div key={i.id}><button className="textlink" onClick={()=>onItem(i.id,s.id)}>問題 {i.no} · {i.topic} →</button><p className="muted">推定正答確率 {(probability(estimate(s).theta,i.id)*100).toFixed(1)}%で不正解</p></div>;return <tr key={s.id}><td><button className="textlink" onClick={()=>onStudent(s.id)}>{s.id}</button></td><td>{questions.length}問</td><td>{link(questions[0])}{questions.length>1&&<details><summary>ほか{questions.length-1}問を見る</summary>{questions.slice(1).map(link)}</details>}</td></tr>})}</tbody></table></div>{flagged.length>5&&<button className="textlink below" onClick={()=>setShowAll(!showAll)}>{showAll?'最初の5人だけ表示':`該当する${flagged.length}人をすべて見る`}</button>}</>:<p>該当する生徒はいません。</p>}<p className="footnote">抽出条件：推定正答確率70%以上で不正解の問題がある生徒。</p></div></>}<div className="insightfoot"><button className="primary" onClick={onConsult}><Sparkles size={17}/>AIに指導方針を相談</button></div></section>}
