'use client';
import {items,rate,Student} from './model';
export const parameters=items.map((_,j)=>({a:0.85+(j%4)*0.2,b:-1.8+j*0.13}));
export function probability(theta:number,j:number){const {a,b}=parameters[j];return 1/(1+Math.exp(-a*(theta-b)))}
// EAP with a N(0,1) prior on [-5,5]. All sample item parameters are illustrative, not calibrated.
const cache=new Map<string,{theta:number;lo:number;hi:number;sd:number}>();
export function estimate(s:Student){const key=s.answers.join(',');const saved=cache.get(key);if(saved)return saved;const grid=Array.from({length:201},(_,k)=>-5+k*.05);const logs=grid.map(t=>-t*t/2+s.answers.reduce((v,y,j)=>{const p=probability(t,j);return v+Math.log(y===1?p:1-p)},0));const max=Math.max(...logs);const w=logs.map(v=>Math.exp(v-max));const z=w.reduce((a,b)=>a+b,0);const weights=w.map(v=>v/z);const theta=grid.reduce((v,t,k)=>v+t*weights[k],0);let cum=0,lo=grid[0],hi=grid[grid.length-1],found=false;grid.forEach((t,k)=>{cum+=weights[k];if(!found&&cum>=.025){lo=t;found=true}if(cum<.975)hi=t+.05});const result={theta,lo,hi,sd:Math.sqrt(grid.reduce((v,t,k)=>v+(t-theta)**2*weights[k],0))};cache.set(key,result);return result}
export function expected(ss:Student[],j:number){return ss.length?ss.reduce((v,s)=>v+probability(estimate(s).theta,j),0)/ss.length*100:null}
export function needsReview(s:Student,j:number){return s.answers[j]===0&&probability(estimate(s).theta,j)>=.7}
export function ReviewLegend(){return <p className="review-legend"><span className="review-tag">要確認</span> 薄いピンク：推定正答確率70%以上で不正解。解答過程を確認したい問題です。70%はモック用の仮基準で、理解不足を断定するものではありません。</p>}
export function advice(s:Student,j:number){const p=probability(estimate(s).theta,j);const y=s.answers[j];return y===-1?{label:'未回答の理由を確認',action:'時間不足か、着手できなかったのかを本人に確認し、最初の手順を説明してもらいましょう。'}:y===0&&p>=.7?{label:'正答が期待される問題',action:'解き方を口頭で説明してもらい、条件の読み違い・計算ミス・理解の抜けを切り分けましょう。'}:y===1&&p<=.4?{label:'理解の広がりを確認',action:'なぜその解き方を選んだか説明してもらい、関連する問題でも考え方を使えるか確認しましょう。'}:y===0?{label:'途中の理解を確認',action:'どの手順まで自力で進めたかを確認し、最初につまずいた箇所を一緒に整理しましょう。'}:{label:'今回の正解を確認',action:'関連する問題の結果も確認し、同じ考え方を説明できていれば次の内容へ進むことを検討しましょう。'}}
export function IrtPersonal({student:s,onItem}:{student:Student;onItem:(j:number)=>void}){const e=estimate(s);const priority=items.filter(i=>s.answers[i.id]!==1).sort((a,b)=>probability(e.theta,b.id)-probability(e.theta,a.id)).slice(0,3);return <section className="card below irt-section"><div className="between"><div><p className="eyebrow">IRT · 個別の指導につなげる</p><h2>この生徒の結果で確認したいこと</h2></div><span className="badge">2PLモデルによる計算例</span></div><div className="irt-metrics"><div><p>推定学力値 θ</p><b>{e.theta.toFixed(2)}</b></div><div><p>推定の幅（95%信用区間）</p><b>{e.lo.toFixed(2)} ～ {e.hi.toFixed(2)}</b></div><div><p>事後標準偏差</p><b>{e.sd.toFixed(2)}</b></div></div><p className="muted">IRTの学力値とLRTの学習段階は別の指標です。θは正答率や偏差値ではありません。</p><ReviewLegend/><div className="irt-actions">{priority.map(i=><article key={i.id} className={needsReview(s,i.id)?'irt-review':undefined}>{needsReview(s,i.id)&&<span className="review-tag">要確認</span>}<span className="badge">{advice(s,i.id).label}</span><h3>問題 {i.no} · {i.topic}</h3><p>推定正答確率 <b>{(probability(e.theta,i.id)*100).toFixed(1)}%</b> / 実際：{s.answers[i.id]===-1?'未回答':'不正解'}</p><p className="irt-next"><b>先生が確認すること</b><br/>{advice(s,i.id).action}</p><button className="textlink" onClick={()=>onItem(i.id)}>問題・答案を確認 →</button></article>)}</div><details className="below"><summary>全24問の推定正答確率・正誤・指導の提案を見る</summary><div className="scrolltable"><table><thead><tr><th>問題・学習項目</th><th>推定正答確率</th><th>実際の結果</th><th>確認・指導の提案</th></tr></thead><tbody>{items.map(i=><tr key={i.id} className={needsReview(s,i.id)?'irt-review':undefined}><td><button className="textlink" onClick={()=>onItem(i.id)}>{i.no}</button><p>{i.topic}</p></td><td><b>{(probability(e.theta,i.id)*100).toFixed(1)}%</b><div className="track"><div style={{width:probability(e.theta,i.id)*100+'%'}}/></div></td><td>{s.answers[i.id]===1?'○ 正解':s.answers[i.id]===0?'× 不正解':'— 未回答'}{needsReview(s,i.id)&&<span className="review-tag">要確認</span>}</td><td className="irt-wrap"><b>{advice(s,i.id).label}</b><p>{advice(s,i.id).action}</p></td></tr>)}</tbody></table></div></details><IrtNotes/></section>}
export function IrtSummary({students:ss,onItem,onStudents}:{students:Student[];onItem:(j:number)=>void;onStudents:(j:number)=>void}){const rows=items.map(i=>{const exp=expected(ss,i.id);return {i,exp,actual:rate(ss,i.id),gap:exp===null?0:rate(ss,i.id)-exp}}).sort((a,b)=>a.gap-b.gap);return <section className="card below irt-section"><div className="between"><div><p className="eyebrow">IRT · 比較から指導へ</p><h2>学力を考慮しても、確認したい学習内容</h2></div><span className="badge">受け持ちの生徒 {ss.length}人</span></div><p className="below muted">全受験者の正答率に加え、受け持ちの生徒の予測正答率と実際の正答率を比べます。予測正答率は、受け持ちの生徒それぞれの推定学力から計算しています。</p>{!ss.length?<p className="callout">対象の生徒がいないため比較できません。</p>:<div className="irt-actions">{rows.slice(0,3).map(({i,exp,actual,gap})=><article key={i.id}><h3>{i.topic}</h3><p className="muted">問題 {i.no}</p><div className="irt-comparison"><span>全受験者の正答率<b>{i.overall.toFixed(1)}%</b></span><span>受け持ちの生徒の予測正答率<b>{exp?.toFixed(1)}%</b></span><span>受け持ちの生徒の実際の正答率<b>{actual.toFixed(1)}%</b></span></div><p>全受験者の正答率との差 <b>{(actual-i.overall).toFixed(1)}ポイント</b><br/>予測正答率との差 <b>{gap.toFixed(1)}ポイント</b></p><p className="irt-next"><b>注意したいポイント</b><br/>{gap<0?'学力から予測した正答率を下回っています。同じ問題で不正解が重なっていることが注目点です。共通する理解の抜けがあるのか、個別の誤りなのかは、この結果だけでは特定できません。':'予測正答率を下回る傾向はありません。ただし、集計では個々の生徒のつまずきが見えにくい点に留意が必要です。'}</p><div className="actions"><button className="textlink" onClick={()=>onItem(i.id)}>根拠の問題 →</button><button className="textlink" onClick={()=>onStudents(i.id)}>不正解の生徒 {ss.filter(s=>s.answers[i.id]===0).length}人 →</button></div></article>)}</div>}<details className="below"><summary>全問題の比較値を見る</summary><div className="scrolltable"><table><thead><tr><th>問題</th><th>全受験者の正答率</th><th>受け持ちの生徒の予測正答率</th><th>受け持ちの生徒の実際の正答率</th><th>予測正答率との差</th></tr></thead><tbody>{rows.map(({i,exp,actual,gap})=><tr key={i.id}><td><button className="textlink" onClick={()=>onItem(i.id)}>{i.no}</button></td><td>{i.overall}%</td><td>{exp?.toFixed(1)??'—'}%</td><td>{ss.length?actual.toFixed(1)+'%':'—'}</td><td>{ss.length?gap.toFixed(1)+'ポイント':'—'}</td></tr>)}</tbody></table></div></details><IrtNotes/></section>}
export function IrtNotes(){return <details className="irt-notes"><summary>正答確率の読み方・計算条件</summary><p>問題の難易度・識別力は架空の値です。その値と実際に表示しているサンプル正誤から、2PLモデル（D=1）・標準正規事前分布のEAPでθを計算しています。実データで較正した分析結果ではありません。</p><p>推定正答確率＝1 / (1 + exp(−a(θ−b)))。受け持ちの生徒の期待正答率は、受け持ちの生徒それぞれの推定正答確率の平均です。未回答は今回の計算では非正答として扱い、画面では不正解と区別します。</p><p>同じ解答から推定した学力との照合であり、独立した未来予測ではありません。1問の不正解だけで理解不足や指導不足とは判断しません。正答確率は技能の習得確率ではありません。</p><p>個別表示の70%・40%は提案の見せ方を確認するための仮基準です。推定の幅・問題品質・関連問題・答案を合わせて判断してください。各回のθは共通尺度未検証のため、直接比較しません。</p></details>}
