'use client';
import {rounds,Student,students} from './model';
export function scoreSummary(values:number[]){if(!values.length)return null;const v=[...values].sort((a,b)=>a-b);const q=(p:number)=>{const x=(v.length-1)*p,i=Math.floor(x);return v[i]+(v[Math.min(i+1,v.length-1)]-v[i])*(x-i)};return {n:v.length,min:v[0],q1:q(.25),median:q(.5),q3:q(.75),max:v[v.length-1],mean:v.reduce((a,b)=>a+b,0)/v.length}}
type Summary=NonNullable<ReturnType<typeof scoreSummary>>;
export default function ScoreBoxes({groups,mode,studentId,schoolAverage}:{groups:Student[][];mode:string;studentId:string;schoolAverage:number|null}){
const personal=mode==='person';
const data=rounds.map((r,k)=>{const person=groups[k].find(s=>s.id===studentId);const local=personal?(person?students(k).filter(s=>s.school===person.school&&s.cls===person.cls):[]):groups[k];const mock=(avg:number,n:number):Summary=>({n,min:8,q1:avg-15,median:avg+1,q3:avg+16,max:100,mean:avg});return {r,person,sets:[{name:personal?'本人のクラス':'受け持ちの生徒',color:'#087f83',value:scoreSummary(local.map(s=>s.score))},{name:'学校全体',color:'#7696af',value:schoolAverage===null?null:mock(schoolAverage,120)},{name:'全受験者',color:'#b08048',value:mock(62.6,2400)}]}});
const width=Math.max(700,rounds.length*210+120),height=350,L=60,R=30,T=30,B=75;const step=(width-L-R)/rounds.length,x=(k:number)=>L+step*(k+.5),y=(v:number)=>T+(100-v)/100*(height-T-B);
return <section className="below"><div className="sectionhead"><h2>得点分布の推移</h2><span className="muted">各回100点満点</span></div><div className="legend">{data[0]?.sets.filter(s=>s.value).map(s=><span key={s.name}><i style={{background:s.color}}/>{s.name}</span>)}{personal&&<span>◆ 本人の得点</span>}<span>● 平均点</span></div><p className="muted">箱：中央の50%の生徒がいる範囲 ／ 箱の中の線：中央値 ／ ひげ：最低点〜最高点</p><div className="trend-scroll" tabIndex={0} aria-label="各回の得点分布。左右にスクロールできます"><svg role="img" aria-label="集団別の箱ひげ図。詳細数値は下の表で確認できます" viewBox={`0 0 ${width} ${height}`} style={{width:'100%',minWidth:width}}>{[0,20,40,60,80,100].map(v=><g key={v}><line x1={L} x2={width-R} y1={y(v)} y2={y(v)} stroke="#e1e9ee"/><text x={L-12} y={y(v)+4} textAnchor="end">{v}</text></g>)}{data.map((d,k)=><g key={k}>{d.sets.map((s,j)=>{const v=s.value,cx=x(k)+(j-1)*48;if(!v)return null;return <g key={s.name}><title>{d.r.name+' / '+s.name+' / '+v.n+'人 / 中央値 '+v.median.toFixed(1)+'点 / 平均 '+v.mean.toFixed(1)+'点'}</title><line x1={cx} x2={cx} y1={y(v.max)} y2={y(v.min)} stroke={s.color}/>{[v.min,v.max].map((n,i)=><line key={i} x1={cx-10} x2={cx+10} y1={y(n)} y2={y(n)} stroke={s.color}/>)}<rect x={cx-15} y={y(v.q3)} width={30} height={Math.max(1,y(v.q1)-y(v.q3))} fill={s.color} fillOpacity={.18} stroke={s.color}/><line x1={cx-15} x2={cx+15} y1={y(v.median)} y2={y(v.median)} stroke={s.color} strokeWidth={2.5}/><circle cx={cx} cy={y(v.mean)} r={3} fill={s.color}/></g>})}<text x={x(k)} y={height-43} textAnchor="middle">第{k+1}回</text><text x={x(k)} y={height-20} textAnchor="middle">{d.sets[0].value?d.sets[0].value.n+'人':'対象の結果なし'}</text></g>)}{personal&&data.map((d,k)=>d.person?<g key={k}>{k>0&&data[k-1].person&&<line x1={x(k-1)-48} x2={x(k)-48} y1={y(data[k-1].person!.score)} y2={y(d.person.score)} stroke="#193544" strokeWidth={2}/>}<path d={`M ${x(k)-48} ${y(d.person.score)-6} l 6 6 -6 6 -6 -6 Z`} fill="#193544"/><text x={x(k)-48} y={y(d.person.score)-12} textAnchor="middle">{d.person.score}点</text></g>:null)}</svg></div><p className="footnote">学校全体・全受験者の箱ひげ図は、表示を確認するための架空の集計値です。平均点から分布を推定したものではありません。本人のクラス・受け持ちの生徒はモックの個別得点から集計しています。</p><p className="footnote">問題の難しさや受験者が回によって異なるため、得点分布の変化だけで学力の伸びとは判断できません。本人の結果がない回は線をつなぎません。</p><details className="below"><summary>箱ひげ図の人数・数値を表で確認</summary><div className="trend-scroll"><table><thead><tr>{['実施回','集団','人数','最低点','第1四分位数','中央値','第3四分位数','最高点','平均点'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{data.flatMap(d=>d.sets.map(s=><tr key={d.r.name+s.name}><td>{d.r.name}</td><td>{s.name}</td><td>{s.value?.n??'—'}</td>{(['min','q1','median','q3','max','mean'] as const).map(key=><td key={key}>{s.value?s.value[key].toFixed(1):'—'}</td>)}</tr>))}</tbody></table></div></details></section>
}