'use client';
import {items} from './model';
import {parameters} from './irt-feedback';
export default function TestComposition(){
 const total=items.reduce((n,i)=>n+i.point,0);
 const areas=[...new Set(items.map(i=>i.area))].map(area=>{const list=items.filter(i=>i.area===area);return {area,count:list.length,points:list.reduce((n,i)=>n+i.point,0)}}).sort((a,b)=>b.points-a.points);
 const bins=[{label:'−2未満',min:-Infinity,max:-2},{label:'−2〜−1未満',min:-2,max:-1},{label:'−1〜0未満',min:-1,max:0},{label:'0〜1未満',min:0,max:1},{label:'1〜2未満',min:1,max:2},{label:'2以上',min:2,max:Infinity}].map(b=>({...b,count:parameters.filter(p=>p.b>=b.min&&p.b<b.max).length}));
 const peak=Math.max(1,...bins.map(b=>b.count));const sparse=areas.filter(a=>a.count<=3);
 return <section className="card test-composition below"><div className="between"><h2>このテストの出題構成・特徴</h2><span className="badge">全{items.length}問 · {total}点満点</span></div><p className="muted">問題の絞り込みにかかわらず、今回のテスト全体の構成を表示しています。</p><div className="grid2"><section><h3>領域別の問題数・配点</h3><p className="muted">棒の長さ：満点に占める配点の割合</p>{areas.map(a=><div className="composition-area" key={a.area}><div className="between"><b>{a.area}</b><span>{a.count}問 ／ {a.points}点（{(a.points/total*100).toFixed(0)}%）</span></div><div className="track"><div style={{width:a.points/total*100+'%'}}/></div></div>)}</section><section><h3>IRTの問題難易度の分布</h3><p className="muted">左ほど易しく、右ほど難しい問題</p><div className="difficulty-chart" role="img" aria-label={bins.map(b=>b.label+'：'+b.count+'問').join('、')}>{bins.map(b=><div className="difficulty-bin" key={b.label}><div className="difficulty-column"><div style={{height:b.count/peak*120}}><span>{b.count}問</span></div></div><span>{b.label}</span></div>)}</div><p className="footnote">横軸：問題難易度 b ／ 縦軸：問題数。全受験者の正答率とは別の指標です。</p></section></div><div className="callout"><b>出題構成から分かること</b><p>「{areas[0].area}」の配点が最も多く、全体の{(areas[0].points/total*100).toFixed(0)}%を占めます。この領域の結果が総得点に比較的大きく影響する構成です。</p>{sparse.length>0&&<p>「{sparse.map(a=>a.area).join('」「')}」は各3問以下です。少数の問題の結果だけで、領域全体の得意・不得意を判断しないよう留意が必要です。</p>}</div><details><summary>出題のねらい・構成の数値を見る</summary><p className="muted">テスト事業者による出題のねらい・到達基準は未提供です。出題数や難易度の分布だけから、テストの目的や習得状況は判断できません。</p><table><thead><tr><th>領域</th><th>問題数</th><th>配点</th><th>配点の割合</th></tr></thead><tbody>{areas.map(a=><tr key={a.area}><td>{a.area}</td><td>{a.count}問</td><td>{a.points}点</td><td>{(a.points/total*100).toFixed(1)}%</td></tr>)}</tbody></table><p className="footnote">現在のモックでは各回に同じ問題構成を使用しています。難易度の区切りは表示用で、学習段階の境界ではありません。</p></details></section>
}
